kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/yourname/go-drone-hello-world

steps:
  - name: build
    image: golang
    commands:
      - go get
      - go build -o output
      - chmod +x output

  - name: run
    image: golang
    commands:
      - go get
      - go build -o output
      - chmod +x output
      - ./output

# volumes:
#   - name: reports
#     host:
#       path: /home/dev/work/src/github.com/cyantarek/drone-go-git-test/reports
